plugins/tiny.go
Tell me how bad I am at Go, please.
=> Add URL shortener using goo.gl

plugins/net_tools.go
Comment for style :lock_with_ink_pen: (why does this exist)
=> Rename net_tools config and struct

plugins/google.go
=> Add Google plugin

plugins/tvdb.go
=> Add TVDB plugin

plugins/lastseen.go, schema.sql
=> Add lastseen

mux/command.go, plugins/chance.go, plugins/expr.go, plugins/forecast.go, plugins/google.go, plugins/karma.go, plugins/metar.go, plugins/net_tools.go, plugins/tiny.go, plugins/tvdb.go, plugins/url.go, plugins/wikipedia.go
=> Transition plugin help to use struct

plugins/twitter.go
Adds a Twitter provider that can be used by other plugins (looking at links)
=> Add twitter provider

plugins/issues.go, plugins/tiny.go
Add first half of Github issues plugin, ref #30.
=> Add issues plugin

README.md, config.toml
Add some more steps and required config for getting seabird up and running.
=> Additional README information

plugins/karma.go
=> Update karma command to work smarter with no args

plugins/linkproviders/xkcd.go, plugins/url.go, plugins/wikipedia.go, seabird.go
This also adds an XKCD link handler
=> Clean up HTML parsing

bot/auth.go, bot/bot.go, bot/handler.go, bot/mux_basic.go, bot/mux_command.go, bot/mux_mention.go
Things I'm considering:
Things left to do:
=> Large rewrite to make seabird work with belak/irc

bot/bot.go
I'd like to drop irc.Dial and irc.DialTLS, so I'm removing usage from here first.
=> Update connection code

bot/bot.go
I'm going to be removing *irc.Client so I'm moving all required functionality over here.
=> Change to use *irc.Conn

bot/bot.go
This is an initial version.
Possible improvements:
* Optional CAPs
* Track which CAPs are enabled (maybe for seabird-state)
=> Add support for requesting capabilities during plugin load

.travis.yml, config.sample.toml, main.go, plugins/db.go, plugins/forecast.go, plugins/karma.go, plugins/lastseen.go, plugins/phrases.go, plugins/remind.go, seabird/plugin.go
I haven't made any final decisions on this, but I like it so far, even if there are a few strange issues.
I'd like to replace all sqlx calls with gorm, if there aren't any major objections.
=> Experiment with using BoltDB

.travis.yml, mux_basic_test.go, mux_command_test.go
This is initial work for #40
More mux tests incoming
=> Initial set of tests

bot.go
This has been tested and works.
The debug option has been changed from Quiet to Debug in the configuration.
=> Make config more sane and fix newlines in debug output

bot.go, cmd/seabird/main.go
I'm working on some test utils which will make it much easier to test plugins as well, but those will be in a later PR.
=> Small improvements

plugins/channel_track.go, plugins/isupport.go
This will allow us to create sessions and use them for uno and other things.
=> User tracking plugin

plugins/extra/remind.go
Based on #168 with @jsvana's change ideas and some extra dirty hacks.
=> Remind add days

plugins/uno/cards.go, plugins/uno/game.go, plugins/uno/plugin.go
Fixes #210, #217, #232, #234, #235, and #237
=> Uno improvements

plugins/url/youtube.go
Fixes #244
Docs here: https://developers.google.com/youtube/v3/docs/search
=> Display Live or Upcoming for video streams

plugins/extra/issues.go
I'm planning on splitting some of the plugins into separate repos (see the uno repo mentioned, which doesn't exist yet) so I need to make sure it's possible to file issues there.
=> Make it possible to submit issues to other repos

plugins/extra/karma.go
=> Batch karma changes when possible

bot.go, mux_command.go, mux_command_test.go, plugins/extra/chance.go, plugins/extra/karma.go, plugins/extra/lastseen.go, plugins/extra/remind.go
This is due to go-irc v2.0 which removes m.FromChannel as it's not as accurate.
This should fix the build on master.
=> Replace m.FromChannel with b.FromChannel(m)

LICENSE, README.md
=> Switch license to MIT

.travis.yml, plugins/extra/karma.go
=> Add buzzkill mode equivalent for negative karma

plugins/extra/stock.go
Allows users to get the current stock price of various symbols
Fixes #261.
=> Add a stock query plugin

plugins/extra/karma.go
Fixes #299
See http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-06/index.html for more information
=> Fix issue with karma not updating to zero

plugins/extra/runescape.go
This makes use of us always fetching all skills and lets users pass
multiple skills per command.
=> [OSRS] Allow users to pass multiple skills at once

plugins/extra/weight_tracker.go
Allows users to report weights over time. The idea is to eventually compete against other users.
=> Add weight tracking plugin

bot.go, mux_basic.go, mux_command.go, request.go
This PR adds timings to requests and logs them as debug messages.
=> Add request timings

_extra/config.sample.toml, bot.go, go.mod, mux_basic.go, mux_command.go, plugins/extra/watchdog.go, request.go
This command is to be used by an external watchdog to monitor the bot.
The intent is to call this from another bot that will then check
timings and correctness.
Example usage:
```
~watchdog-check {"nonce":"yolo"}
```
=> Add watchdog-check command

README.md, docs/README.md, docs/configuration.md, docs/plugin_configuration_options.md, docs/plugin_development.md, docs/url_plugin_development.md
This PR adds various bits of documentation around configuration and
plugin development.
=> Adds documentation for the bot.
